---
- name: Gather system utilization
  hosts: all
  gather_facts: yes

  tasks:

    - name: Get CPU usage
      shell: "top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}'"
      register: cpu_usage

    - name: Get RAM usage percentage
      shell: "free | grep Mem | awk '{print ($3/$2) * 100}'"
      register: ram_usage

    - name: Get Disk usage percentage for root /
      shell: "df -h / | awk 'NR==2 {print $5}'"
      register: disk_usage

    - name: Return utilization
      debug:
        msg:
          cpu: "{{ cpu_usage.stdout | float | round(2) }}"
          ram: "{{ ram_usage.stdout | float | round(2) }}"
          disk: "{{ disk_usage.stdout }}"
