---
- name: Get system info
  hosts: all
  gather_facts: false
  tasks:
    - name: Get CPU load
      ansible.builtin.command: "grep 'cpu ' /proc/stat"
      register: cpu_output

    - name: Get RAM usage
      ansible.builtin.command: "free -m"
      register: ram_output

    - name: Show system info
      ansible.builtin.debug:
        msg: |
          CPU Info: {{ cpu_output.stdout }}
          RAM Info: {{ ram_output.stdout }}
