---
- name: Gather system info
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get CPU usage
      shell: "top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}'"
      register: cpu_usage

    - name: Get RAM usage
      shell: "free -m | awk 'NR==2{printf \"%s/%sMB (%.2f%%)\", $3,$2,$3*100/$2 }'"
      register: ram_usage

    - name: Get Disk usage
      shell: "df -h / | awk 'NR==2{print $3 \"/\" $2 \" used: \"$5}'"
      register: disk_usage

    - name: Set Telegram message
      set_fact:
        telegram_msg: "Server {{ inventory_hostname }} Status:\nCPU Usage: {{ cpu_usage.stdout }}%\nRAM Usage: {{ ram_usage.stdout }}\nDisk Usage: {{ disk_usage.stdout }}"

    - name: Send message to Telegram
      uri:
        url: "https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "<YOUR_CHAT_ID>"
          text: "{{ telegram_msg }}"
        headers:
          Content-Type: "application/json"
