---
- name: Collect system info
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get CPU usage
      shell: "top -bn1 | grep 'Cpu(s)' | awk '{print $2+$4}'"
      register: cpu_usage

    - name: Get RAM usage
      shell: "free -m | awk 'NR==2{printf \"%s/%sMB\", $3,$2 }'"
      register: ram_usage

    - name: Get Disk usage
      shell: "df -h / | awk 'NR==2{print $3\"/\"$2}'"
      register: disk_usage

    - name: Print system info
      debug:
        msg: |
          CPU Usage: {{ cpu_usage.stdout }}%
          RAM Usage: {{ ram_usage.stdout }}
          Disk Usage: {{ disk_usage.stdout }_
