---
- name: Check Apache service status
  hosts: all
  gather_facts: no
  tasks:
    - name: Check if Apache is running
      ansible.builtin.systemd:
        name: apache2   # لو السيرفر عندك RHEL ممكن يكون httpd
        state: started
      register: apache_status
      ignore_errors: yes

    - name: Return Apache status
      ansible.builtin.debug:
        msg: |
          {% if apache_status is failed %}
          ⚠️ Apache is not running!
          {% else %}
          ✅ Apache is running fine.
          {% endif %}
