---
- name: Check server status
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping servers
      ansible.builtin.ping:

    - name: Check disk usage
      ansible.builtin.shell: df -h /
      register: disk
      ignore_errors: yes

    - name: Fail if disk usage > 90%
      ansible.builtin.fail:
        msg: "Disk usage is above 90%"
      when: disk.stdout_lines[1].split()[4] | int > 90
