---
- name: Check server resources
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get CPU usage
      ansible.builtin.shell: "top -bn1 | grep 'Cpu(s)' | awk '{print 100 - $8}'"
      register: cpu_usage
      changed_when: false

    - name: Get RAM usage percentage
      ansible.builtin.shell: "free | awk '/Mem/ {printf(\"%.2f\", $3/$2 * 100)}'"
      register: ram_usage
      changed_when: false

    - name: Get disk usage percentage
      ansible.builtin.shell: "df -h / | awk 'NR==2 {print $5}' | sed 's/%//g'"
      register: disk_usage
      changed_when: false

    - name: Set fact for resource summary
      ansible.builtin.set_fact:
        resources:
          cpu: "{{ cpu_usage.stdout | float }}"
          ram: "{{ ram_usage.stdout | float }}"
          disk: "{{ disk_usage.stdout | float }}"

    - name: Return JSON for n8n
      ansible.builtin.debug:
        msg: "{{ resources }}"
